import { OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import 'rxjs/add/operator/switchMap';
import { Observable } from 'rxjs/Observable';
import { ConfigService } from '../config/config.service';
import { Product } from '../products/product';
import { ProductsService } from '../products/products.service';
import { ProductImageService } from '../products/product-image.service';
import { ProductImage } from '../products/product-image';
export declare class ProductDetailsComponent implements OnInit {
    private configService;
    private productService;
    private productImageService;
    private route;
    private location;
    product: Product;
    productId: string;
    productImages: Observable<ProductImage[]>;
    file: any;
    awsBucket: string;
    mainImageUrl: string;
    newProduct: boolean;
    private config;
    constructor(configService: ConfigService, productService: ProductsService, productImageService: ProductImageService, route: ActivatedRoute, location: Location);
    ngOnInit(): void;
    goBack(): void;
    save(): void;
    onMainImageChange(): void;
    onImageChange(key: string): void;
    upload(file: any, signed_request: string, url: string, done: any): void;
    delete(file: any, signed_request: string, url: string, done: any): void;
    deleteMainImage(): void;
    afterGetDeleteMainImageAuthorizationHeader(response: any): void;
    afterDeleteMainImage(): void;
    afterSignRequest(response: any): void;
    afterFileUpload(url: string, thisObject: any): void;
    getProductImages(): void;
    addImageOld(): void;
    addImage(): void;
    imageAdded(): void;
    moveImageUp(imageId: string): void;
    moveImageDown(imageId: string): void;
    deleteImage(imageId: string): void;
}
